[package]
name = "day7_handy_haversacks"
version = "0.1.0"
authors = ["HeroN` <khusain444@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
queues = "1.0.0"
